#:schema node_modules/wrangler/config-schema.json
name = "dino"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./public", binding = "ASSETS" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true


[[kv_namespaces]]
binding = "leaderboard"
id = "8f1de07ee0e04b0da06421240f6aca5e"
